// Lead Generation Service - Uses Claude Sonnet via Backend API
// All API keys are securely stored on the server

import { apify, isApifyConfigured } from './api.js';

// Re-export the configured check (checks if Claude API is configured)
export { isApifyConfigured };

// Start AI lead generation
export const scrapeGoogleMaps = async ({ keyword, location, maxResults = 100 }) => {
  return apify.scrape({ keyword, location, maxResults });
};

// Get run status
export const getRunStatus = async (runId) => {
  return apify.getRunStatus(runId);
};

// Get run results - leads generated by Claude
export const getRunResults = async (runId) => {
  return apify.getRunResults(runId);
};

// Wait for lead generation to complete and get results
export const scrapeAndWait = async ({ keyword, location, maxResults = 100 }, onStatusUpdate) => {
  return apify.scrapeAndWait({ keyword, location, maxResults }, onStatusUpdate);
};

// Get recent runs
export const getRecentRuns = async (limit = 10) => {
  return apify.getRecentRuns(limit);
};
